<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlatformProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('platform_profiles')->delete();
        
        \DB::table('platform_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'platform_id' => 3,
                'handle' => 'tourist',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://atcoder.jp/users/tourist',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:46',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'platform_id' => 4,
                'handle' => 'potato167',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.codechef.com/users/potato167',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:46',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 2,
                'platform_id' => 1,
                'handle' => 'tourist',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://codeforces.com/profile/tourist',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:46',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 2,
                'platform_id' => 7,
                'handle' => 'lboris',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.hackerearth.com/@lboris',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 2,
                'platform_id' => 6,
                'handle' => 'Gennady',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.hackerrank.com/profile/Gennady',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 2,
                'platform_id' => 2,
                'handle' => 'cpcs',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://leetcode.com/u/cpcs',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 2,
                'platform_id' => 5,
                'handle' => 'defrager',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.spoj.com/users/defrager',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 2,
                'platform_id' => 9,
                'handle' => '19306',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://acm.timus.ru/author.aspx?id=19306',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 2,
                'platform_id' => 8,
                'handle' => '1133',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://uhunt.onlinejudge.org/id/1133',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-06 11:27:33',
                'updated_at' => '2026-02-08 16:06:47',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 3,
                'platform_id' => 3,
                'handle' => 'e_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://atcoder.jp/users/e_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:02',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 3,
                'platform_id' => 4,
                'handle' => 'e_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.codechef.com/users/e_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:05',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 3,
                'platform_id' => 1,
                'handle' => 'emon_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://codeforces.com/profile/emon_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:12',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 3,
                'platform_id' => 7,
                'handle' => 'e_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.hackerearth.com/@e_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:28',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 3,
                'platform_id' => 6,
                'handle' => 'e_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.hackerrank.com/profile/e_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:50',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 3,
                'platform_id' => 2,
                'handle' => 'emon1432',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://leetcode.com/u/emon1432',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:29:57',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 3,
                'platform_id' => 5,
                'handle' => 'e_mon',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://www.spoj.com/users/e_mon',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:30:28',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 3,
                'platform_id' => 9,
                'handle' => '405359',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://acm.timus.ru/author.aspx?id=405359',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:30:37',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 3,
                'platform_id' => 8,
                'handle' => '1135924',
                'platform_user_id' => NULL,
                'name' => NULL,
                'avatar_url' => NULL,
                'joined_at' => NULL,
                'ranking' => NULL,
                'rating' => NULL,
                'total_solved' => 0,
                'profile_data' => NULL,
                'profile_url' => 'https://uhunt.onlinejudge.org/id/1135924',
                'profile_source' => 'api',
                'visibility_status' => NULL,
                'status' => 'Active',
                'last_synced_at' => NULL,
                'captured_at' => NULL,
                'last_sync_status' => NULL,
                'last_sync_error' => NULL,
                'last_sync_duration_ms' => NULL,
                'sync_attempts' => 0,
                'created_at' => '2026-02-09 08:28:10',
                'updated_at' => '2026-02-09 08:31:11',
            ),
        ));
        
        
    }
}